### ISSUE TITLE
Add placeholder image below the homepage message. 

### ISSUE THREAD

**Issue by sagargg-zz** [datopian/ckanext-iaea#12]
# Acceptance Criteria 

* [ ] I can see the placeholder image below the message on the homepage 

# Tasks 
* [x] Ask IEAE team to provide a placeholder image. 
* [x] Implement place holder image on homepage.
* [x] Review/Test
* [x] Deploy on dev env.
