### ISSUE TITLE
Add text beside the logo 

### ISSUE THREAD

**Issue by sagargg-zz** [datopian/ckanext-iaea#13]
# Acceptance Criteria 
* [ ] I can see the  "Open Data Platform" text is added beside the logo. 

# Tasks 
* [x] Update template adding "Open Data Platform" text.
* [x] Review/Test
* [x] Deopy on dev env.
