### ISSUE TITLE
Azure active directory  SSO using OAuth2  extension 

### ISSUE THREAD

**Issue by sagargg-zz** [datopian/ckanext-iaea#17]
# Acceptance Criteria 
* [ ]  I'm able to log in with my Microsoft account. 

# Tasks 
* [x] Ask IEAE to provide AD credientials for dev env. 
* [ ] Install and enable`ckanext-oauth2` extension. 
* [ ] Add/configure required environment variable. 
* [ ] Test/Review
* [ ] Deploy dev env.
