### ISSUE TITLE
Remove organization from the navbar

### ISSUE THREAD

**Issue by sagargg-zz** [datopian/ckanext-iaea#2]
# Acceptance criteria 
*  [ ]  I can see the menu only with Topics and Datasets and Search. The organization is removed from the menu.

# Task
* [x] Extend templates on custom extension. 
* [x] Review, test, Deploy.
