### ISSUE TITLE
The dataset owner should be able to track how users are interacting with the dataset and when they are downloading data

### ISSUE THREAD

**Issue by sagargg-zz** [datopian/ckanext-iaea#22]
**AZURE ISSUE :**  [#55698 ](https://iaeabss.visualstudio.com/IAEA%20Data%20Platform/_boards/board/t/IAEA%20Data%20Platform%20Team/Backlog%20items/?workitem=55698)

## Acceptance Criteria
* [ ]  As a dataset owner, I'm able to t track how users are downloading their datasets.

## Tasks
* [x]  Create a GA Property for dev propose. 
* [x]  Install/enable GA extension.
* [x]  Create a download reports
