### ISSUE TITLE
Data explorer bug fixes 

### ISSUE THREAD

**Issue by sagargg-zz** [datopian/ckanext-iaea#24]
**AZURE ISSUE :** [#57752](https://iaeabss.visualstudio.com/IAEA%20Data%20Platform/_boards/board/t/IAEA%20Data%20Platform%20Team/Backlog%20items/?workitem=57752)

# Acceptance Criteria 
* [ ] I  can see all below-listed bugs are resolved.

# Tasks 
* [x] Table should be presented before the chart
* [x]   For a large dataset, it is hard to find the horizontal scroll
Example 
https://ckan.iaea.dev.datopian.com/dataset/imagine-iaea-medical-imaging-and-nuclear-medicine/resource/526f0435-6f67-460a-a522-d9d9267cf85d?view_id=71948ce2-c4f2-4bf9-93c7-c6a7cb63cfb0
* [x]  When a filter is applied, the table come with extra empty rows![image](https://user-images.githubusercontent.com/11631101/119926627-7216dd00-bf97-11eb-9cfc-695f0c7b4c3b.png)
* [x]  Two filters are presented with strange css and without label.
