### ISSUE TITLE
Present predefined filters to end users

### ISSUE THREAD

**Issue by sagargg-zz** [datopian/ckanext-iaea#27]
As a Data Publisher, I can define suggested fields for filtering data so that when users land on the page they are prompted with those fields in the filters component.

## Acceptance criteria 

* [ ]  When creating a view for a resource, I can define suggested fields for filtering my data.
* [x]  When landing on the resource page, I am prompted with suggested fields for filtering.

## Tasks

* [x] change data publisher UI to be able to define fields 
* [x] change datastore-query-builder app to pickup initial state from the view spec
* [ ] build, release, deploy 

## Analysis

The view object would have an additional attribute for storing suggested fields for filtering:

Data Explorer view:

```
{
  "description": "",
  "title": "My view title",
  "resource_id": "xxx",
  "view_type": "dataexplorer_view",
  "id": "xxx",
  "package_id": "xxx"
}
```

Data Explorer - Table only view:

```
{
  "description": "",
  "title": "Table",
  "resource_id": "xxx",
  "view_type": "dataexplorer_table_view",
  "id": "xxx",
  "package_id": "xxx"
}
```

We can add `suggested_filter_fields` attribute so that:

```
{
  "description": "",
  "title": "My view title",
  "resource_id": "xxx",
  "view_type": "dataexplorer_view",
  "id": "xxx",
  "package_id": "xxx",
  "suggested_filter_fields": ["column a", "column b"]
}
```

On "create view" page, we need to add another option to add suggested filter fields which can unchecked checkboxes with column names so that admin checks the fields that should be suggested for filtering.

Make sure the `suggested_filter_fields` is converted to `rules`.

Next, is to parse it and use as initial state in the query builder app:

1. Create a new fixture for Cosmos in Datastore Query Builder app. The `resource` object can be something like:

```javascript
import { QueryBuilder } from '../src/App.js'


const resource = {
  name: 'test',
  id: 'some-random-id',
  path: 'https://montreal-staging-site.ca/datastore/dump/some-random-id',
  schema: {
    fields: [
      {
        name: 'a',
        type: 'string'
      },
      {
        name: 'b',
        type: 'string'
      },
      {
        name: 'c',
        type: 'string'
      }
    ]
  },
  rules: [{
      'combinator': 'AND',
      'field': 'xx',
      'operator': '=',
      'value': 'x'
    },
    {
      'combinator': 'AND',
      'field': 'xxx',
      'operator': '<',
      'value': 'x'
    }],
  date: {
     startDate: null,
     endDate: null,
     fieldName: 'xxx'
   } 
 }
 

const filterBuilderAction = (resource) => {
  alert(JSON.stringify(resource))
}

export default {
  component: QueryBuilder,
  props: {resource, filterBuilderAction}
};
```

2. Change this line https://github.com/datopian/datastore-query-builder/blob/master/src/DatastoreSearchSql.js#L89 to:

```javascript
rules: resource.rules || [],
```
3. Test it in Cosmos.
