### ISSUE TITLE
Update introductory text  on the homepage

### ISSUE THREAD

**Issue by sagargg-zz** [datopian/ckanext-iaea#3]
# Acceptance criteria 
* [ ] Update introductory text as shown on the given [image](https://iaeabss.visualstudio.com/8b9e655c-d041-41e1-b465-cb29aa0036f7/_apis/wit/attachments/a98d5a1c-76bb-4d85-b393-f8e36029fe37?fileName=image.png).  

# Task
* [x] Extend and update template on custom extension. 
* [x]  review
* [x] deploy on dev env.
