### ISSUE TITLE
Disable publishing data without organization for all envs

### ISSUE THREAD

**Issue by sagargg** [datopian/ckanext-iaea#33]
## Acceptance Criteria
* [ ] I can see users who have not associated with any organization not able to publish datasets. 

## Task
* [x] Update deployment configuration to disable publishing data without organization for all envs. 
* [x] Deploy to all environments. 
* [ ] Test
