### ISSUE TITLE
Whitelist IP range provided by Lauren

### ISSUE THREAD

**Issue by sagargg** [datopian/ckanext-iaea#34]
## Acceptance Criteria  
- [x]  I can see the Dev and Staging env only works for whitelisted IPs. 

## Tasks
- [x]  Add a whitelisted IP range on k8s  helm annotations chat. 
- [x] Add for Dev and Staging environment 
- [x] Test and confirm it's working as expected.
