### ISSUE TITLE
Estimate installing Web Map Service (WMS) support extension on all envs. 

### ISSUE THREAD

**Issue by sagargg** [datopian/ckanext-iaea#36]
## Acceptance Criteria 
- [x] I have provided the estimate for installing the WMS support extension on all envs. 

## Tasks
- [x] Analysis and find WMS support CKAN extension.
- [x] Share the estimate within the team and client. 

## Estimates
We estimated 1 hour to install this extension. 
https://github.com/ckan/ckanext-geoview
