### ISSUE TITLE
List topics on the home page with image, description and sort with dataset number. 

### ISSUE THREAD

**Issue by sagargg-zz** [datopian/ckanext-iaea#4]
# Acceptance Criteria
* [ ] I can see the list of the topics with image, description, and sort with dataset number. 

# Tasks
* [x] Write helper function with logic.
* [x] Update on the template.
* [x] Reveiw
* [x] Deploy on the dev env.
