### ISSUE TITLE
Estimate and Implement  SSO login as default login.

### ISSUE THREAD

**Issue by sagargg** [datopian/ckanext-iaea#40]
## Acceptance Criteria
* [x] I can see the following tasks are completed and working as expected.

## Tasks 
* [x] Replace login button link on a top header with SSO link/controller. 
* [x] Remove the register button and log out. 
* [x] Restric traditional login/register page. 
* [x] Redirect the home page as default after the user logged in insestead the dashboard page. 

## Analysis
We can disable traditional login with a simple configuration in the `ckanext-saml2auth` extension. `ckanext.saml2auth.enable_ckan_internal_login = True`

1. Replace the login button link on the top header with the SSO link/controller. [Configurable]
2. Remove the register button and log out.  [Configurable]
3. Restric traditional login/register page.  [Configurable]
4. Redirect the home page as default after the user logged in instead of the dashboard page.  [30 min]

## Estimate
We estimated 1.5 Hours to implement the above items with buffer time.
