### ISSUE TITLE
Display selected view from the resource in dataset page

### ISSUE THREAD

**Issue by sagargg** [datopian/ckanext-iaea#41]
The client is interested to have views on the dataset page similar to the [HDX dataset ](https://data.humdata.org/dataset/fts-requirements-and-funding-data-for-occupied-palestinian-territory)page.  

## Acceptance Criteria 
- [ ]  Discuss the implementation approach and provide an estimate. 

## Tasks 
- [ ]  Analysis of how it can be implemented.   [30 min]
- [ ]  Add a new field to the views to store the state of selection eg. `featured_dataset: true`. [est. 1 hr]
    - The [config DB](https://github.com/ckan/ckan/blob/master/ckan/model/resource_view.py#L26) field is useful to store the selection state. 
- [ ] Create a helper function and action to return available all views from the dataset. eg `package_views_list`    [est. 2 hr]
- [ ] Add a new tab in the dataset template and implement  UI inside that tab for users to select views.  (with checkbox and submit button) [ est. 1.5hr]
- [ ] Create a controller to save the selected view in the database.  [est. 1.5 hr]

- Buffer to handle any contingencies - 1 hr

**TOTAL ESTIMATE:**  7.5

## Implementation approach 
The idea is to add new tab `views` on the dataset page where the user sees all views and selects one of them to display it on the dataset page. 
ex:
<img width="1401" alt="Screen Shot 2022-04-22 at 9 07 00 AM" src="https://user-images.githubusercontent.com/87696933/164590184-de98705b-22bc-4f07-bdee-f7d92413a92b.png">
