### ISSUE TITLE
IAEA address  address on footer.

### ISSUE THREAD

**Issue by sagargg-zz** [datopian/ckanext-iaea#7]
# Acceptance Criteria 
* [ ] I can see a footer the have  IEAE address, ckan attribution (Power By Ckan) and i18n select option.  All links from the left-hand side are removed. 

# Tasks
* [x]  Update template on extension. 
* [x]  Test/Reveiw
* [x]  Deploy dev env
